desc "Remove 'backup swap autoload vim-pathogen' folders"
task :clean do
  dirs = %w(backup swap autoload vim-pathogen).map{|dir| File.expand_path dir}
  FileUtils.rm_rf(dirs)
end

desc "Install vim bundles"
task :install do
  prepare_install
  sh "cd .. && git submodule sync >/dev/null"
  sh "cd .. && git submodule update --init"
end

desc "Upgrade bundles from its upstream"
task :upgrade_submodule do
  system "cd .. && git submodule foreach ' git pull --quiet --ff-only --no-rebase origin master '"
end

def prepare_install
  dirs = %w(backup swap).map{|dir| File.expand_path dir}
  FileUtils.mkdir_p(dirs)

  #install vim-pathogen.git
  sh "git clone git://github.com/tpope/vim-pathogen.git vim-pathogen --depth=1"
  FileUtils.cd "vim-pathogen" do
    FileUtils.mv("autoload", "..")
  end
  FileUtils.rm_rf("vim-pathogen")
end

desc "Build CommandT plugin"
task :build_command_t do
  Dir.chdir "bundle/Command-T/ruby/command-t" do
    sh "ruby extconf.rb"
    sh "make clean && make"
  end
end

task :default => [:clean, :install, :build_command_t]
