desc "Install vim bundles"
task :install do
  sh "cd .. && git submodule sync >/dev/null"
  sh "cd .. && git submodule update --init"
end

desc "Upgrade bundles from its upstream"
task :upgrade do
  system "cd .. && git submodule foreach ' git pull --quiet --ff-only --no-rebase origin master '"
end

desc "Build CommandT plugin"
task :build_command_t do
  Dir.chdir "bundle/Command-T/ruby/command-t" do
    sh "ruby extconf.rb"
    sh "make clean && make"
  end
end

task :default => [:install, :build_command_t]
