export PATH=~/.dotfiles/bin:/usr/local/bin:/usr/local/sbin:$PATH

# locale stuff
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
set encoding=utf-8 nobomb

export EDITOR='vim'

if [[ "$TERM_PROGRAM" =~ iTerm|Apple_Terminal ]] && [[ -x "`which mvim`" ]]; then
  export EDITOR='mvim -f'
  export BUNDLER_EDITOR='mvim'
  export GEM_EDITOR='mvim'
fi

# history
export HISTCONTROL=ignoredup # don't put duplicate lines in the history.s
export HISTFILESIZE=3000
export HISTIGNORE="ls:cd:[bf]g:exit:..:...:ll:lla"
shopt -s histappend # Append to the Bash history file, rather than overwriting it

# autofix typos
shopt -s cdspell

# aliases
alias ls='ls -G'  # OS-X SPECIFIC - the -G command in OS-X is for colors, in Linux it's no groups

# disk usage with human sizes
alias du1='du -hs'

# lists folders and files sizes in the current folder
alias ducks='du -cksh * | sort -rn|head -11'

alias ll='ls -AFGHhl'

alias reloadbash='source ~/.bash_profile'

#http heaers en1 (airport)
alias sniff_headers="sudo tcpflow -c -p -i en0 | httpflow.py"

alias uninstall_all_gems='gem list |cut -d" " -f1|xargs gem uninstall -aIx'

alias gemdep="gem dependency"

alias be="bundle exec"

alias psg="ps aux | egrep -i --color"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# load Homebrew's shell completion
if which brew > /dev/null && [ -f "$(brew --prefix)/Library/Contributions/brew_bash_completion.sh" ]
then
  source "$(brew --prefix)/Library/Contributions/brew_bash_completion.sh"
fi

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

# Invitation
# <new line><user>:<current_directory> git_branch <new line> <prompt>
export PS1="\n\u:\w \[\e[1;32m\]\$(__git_ps1 '%s')\[\e[0m\] \n→ "

#chruby
. /usr/local/opt/chruby/share/chruby/chruby.sh
RUBIES=(~/.chruby/*)

# node version manager
if [ -f ~/.nvm/nvm.sh ]; then
  . ~/.nvm/nvm.sh
fi

# grep by file name
ff(){
  find . | grep $@
}

# push SSH public key
push_ssh_cert() {
  local _host
  test -f ~/.ssh/id_rsa.pub || ssh-keygen -t dsa
  for _host in "$@";
  do
    echo $_host
    ssh $_host 'cat >> ~/.ssh/authorized_keys' < ~/.ssh/id_rsa.pub
  done
}

# make port 80 "real life" speeds. You can also use Mongrel ports.
slow_port() {
  # Set the port variable if no port inputted. Defaulted to 80 (for Passenger).
  if [ -z "$1" ]
  then port=80
  else port=$1
  fi

  # Slow the ports.
  sudo ipfw pipe 1 config bw 100KByte/s
  sudo ipfw add 1 pipe 1 src-port $port
  sudo ipfw add 1 pipe 1 dst-port $port
  echo "Port $port succesfully slowed."
}

unslow_port() {
  sudo ipfw delete 1
  echo "Port succesfully un-slowed."
}

if [ -f ~/.localrc ]; then
  . ~/.localrc
fi

# startup virtualenv-burrito
if [ -f $HOME/.venvburrito/startup.sh ]; then
    . $HOME/.venvburrito/startup.sh
fi
