" Spellchek
setlocal spell spelllang=
setlocal nospell
function ChangeSpellLang()
  if &spelllang =~ "en_us"
    setlocal spell spelllang=ru
    echo "spelllang: ru"
  elseif &spelllang =~ "ru"
    setlocal spell spelllang=
    setlocal nospell
    echo "spelllang: off"
  else
    setlocal spell spelllang=en_us
    echo "spelllang: en"
  endif
endfunc

" Spellchek hotkey
map <D-F11> :call ChangeSpellLang()<CR>

" Start without the toolbar
set guioptions-=T
set guioptions-=L

" set no scroll
set guioptions-=r

set showtabline=2

if has("gui_macvim")
  " Fullscreen mode takes the whole screen
  set fuopt=maxvert,maxhorz

  set guifont=Monaco:h16

  " Antialias font
  set antialias

  " Command-f for CommandT
  macmenu &Edit.Find.Find\.\.\. key=<nop>
  map <D-f> :CommandT<CR>

  " Command-Shift-F for Ack
  macmenu Window.Toggle\ Full\ Screen\ Mode key=<nop>
  map <D-F> :Ack --ignore-dir=public <space>

  "Command-/ to toggle comments
  map <D-/> <plug>NERDCommenterToggle<CR>
elseif has("gui_gtk2")
  set guifont=Monaco
end

if filereadable("~/.gvimrc.local")
    so ~/.gvimrc.local
endif
